/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BackendRouteRouteImport } from './routes/backend/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BundlesIndexRouteImport } from './routes/bundles/index'
import { Route as BackendIndexRouteImport } from './routes/backend/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as BundleSlugRouteImport } from './routes/bundle/$slug'
import { Route as BackendUsersRouteImport } from './routes/backend/users'
import { Route as BackendSubmissionsRouteImport } from './routes/backend/submissions'
import { Route as BackendSiteSettingsRouteImport } from './routes/backend/site-settings'
import { Route as BackendSettingsRouteImport } from './routes/backend/settings'
import { Route as BackendProductsRouteImport } from './routes/backend/products'
import { Route as BackendPagesRouteImport } from './routes/backend/pages'
import { Route as BackendOrdersRouteImport } from './routes/backend/orders'
import { Route as BackendNewsletterRouteImport } from './routes/backend/newsletter'
import { Route as BackendNavLinksRouteImport } from './routes/backend/nav-links'
import { Route as BackendMediaRouteImport } from './routes/backend/media'
import { Route as BackendLoginRouteImport } from './routes/backend/login'
import { Route as BackendLifestyleCardsRouteImport } from './routes/backend/lifestyle-cards'
import { Route as BackendIntegrationsRouteImport } from './routes/backend/integrations'
import { Route as BackendHomepageSectionsRouteImport } from './routes/backend/homepage-sections'
import { Route as BackendHomepageRouteImport } from './routes/backend/homepage'
import { Route as BackendHeroSlidesRouteImport } from './routes/backend/hero-slides'
import { Route as BackendFeatureCardsRouteImport } from './routes/backend/feature-cards'
import { Route as BackendEmailTemplatesRouteImport } from './routes/backend/email-templates'
import { Route as BackendDataTransferRouteImport } from './routes/backend/data-transfer'
import { Route as BackendContentRouteImport } from './routes/backend/content'
import { Route as BackendCommunicationsRouteImport } from './routes/backend/communications'
import { Route as BackendCommerceRouteImport } from './routes/backend/commerce'
import { Route as BackendCollectionsRouteImport } from './routes/backend/collections'
import { Route as BackendCheckoutRouteImport } from './routes/backend/checkout'
import { Route as BackendCategoriesRouteImport } from './routes/backend/categories'
import { Route as BackendCatalogRouteImport } from './routes/backend/catalog'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendRouteRoute = BackendRouteRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendIndexRoute = BackendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendUsersRoute = BackendUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSubmissionsRoute = BackendSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSiteSettingsRoute = BackendSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSettingsRoute = BackendSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendProductsRoute = BackendProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendPagesRoute = BackendPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendOrdersRoute = BackendOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendNewsletterRoute = BackendNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendNavLinksRoute = BackendNavLinksRouteImport.update({
  id: '/nav-links',
  path: '/nav-links',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendMediaRoute = BackendMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendLoginRoute = BackendLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendLifestyleCardsRoute = BackendLifestyleCardsRouteImport.update({
  id: '/lifestyle-cards',
  path: '/lifestyle-cards',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendIntegrationsRoute = BackendIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHomepageSectionsRoute = BackendHomepageSectionsRouteImport.update({
  id: '/homepage-sections',
  path: '/homepage-sections',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHomepageRoute = BackendHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHeroSlidesRoute = BackendHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendFeatureCardsRoute = BackendFeatureCardsRouteImport.update({
  id: '/feature-cards',
  path: '/feature-cards',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendEmailTemplatesRoute = BackendEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendDataTransferRoute = BackendDataTransferRouteImport.update({
  id: '/data-transfer',
  path: '/data-transfer',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentRoute = BackendContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCommunicationsRoute = BackendCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCommerceRoute = BackendCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCollectionsRoute = BackendCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCheckoutRoute = BackendCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCategoriesRoute = BackendCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCatalogRoute = BackendCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => BackendRouteRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/backend': typeof BackendRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/$': typeof AdminSplatRoute
  '/backend/catalog': typeof BackendCatalogRoute
  '/backend/categories': typeof BackendCategoriesRoute
  '/backend/checkout': typeof BackendCheckoutRoute
  '/backend/collections': typeof BackendCollectionsRoute
  '/backend/commerce': typeof BackendCommerceRoute
  '/backend/communications': typeof BackendCommunicationsRoute
  '/backend/content': typeof BackendContentRoute
  '/backend/data-transfer': typeof BackendDataTransferRoute
  '/backend/email-templates': typeof BackendEmailTemplatesRoute
  '/backend/feature-cards': typeof BackendFeatureCardsRoute
  '/backend/hero-slides': typeof BackendHeroSlidesRoute
  '/backend/homepage': typeof BackendHomepageRoute
  '/backend/homepage-sections': typeof BackendHomepageSectionsRoute
  '/backend/integrations': typeof BackendIntegrationsRoute
  '/backend/lifestyle-cards': typeof BackendLifestyleCardsRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/nav-links': typeof BackendNavLinksRoute
  '/backend/newsletter': typeof BackendNewsletterRoute
  '/backend/orders': typeof BackendOrdersRoute
  '/backend/pages': typeof BackendPagesRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/site-settings': typeof BackendSiteSettingsRoute
  '/backend/submissions': typeof BackendSubmissionsRoute
  '/backend/users': typeof BackendUsersRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/backend/': typeof BackendIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/$': typeof AdminSplatRoute
  '/backend/catalog': typeof BackendCatalogRoute
  '/backend/categories': typeof BackendCategoriesRoute
  '/backend/checkout': typeof BackendCheckoutRoute
  '/backend/collections': typeof BackendCollectionsRoute
  '/backend/commerce': typeof BackendCommerceRoute
  '/backend/communications': typeof BackendCommunicationsRoute
  '/backend/content': typeof BackendContentRoute
  '/backend/data-transfer': typeof BackendDataTransferRoute
  '/backend/email-templates': typeof BackendEmailTemplatesRoute
  '/backend/feature-cards': typeof BackendFeatureCardsRoute
  '/backend/hero-slides': typeof BackendHeroSlidesRoute
  '/backend/homepage': typeof BackendHomepageRoute
  '/backend/homepage-sections': typeof BackendHomepageSectionsRoute
  '/backend/integrations': typeof BackendIntegrationsRoute
  '/backend/lifestyle-cards': typeof BackendLifestyleCardsRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/nav-links': typeof BackendNavLinksRoute
  '/backend/newsletter': typeof BackendNewsletterRoute
  '/backend/orders': typeof BackendOrdersRoute
  '/backend/pages': typeof BackendPagesRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/site-settings': typeof BackendSiteSettingsRoute
  '/backend/submissions': typeof BackendSubmissionsRoute
  '/backend/users': typeof BackendUsersRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/backend': typeof BackendIndexRoute
  '/bundles': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/backend': typeof BackendRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/$': typeof AdminSplatRoute
  '/backend/catalog': typeof BackendCatalogRoute
  '/backend/categories': typeof BackendCategoriesRoute
  '/backend/checkout': typeof BackendCheckoutRoute
  '/backend/collections': typeof BackendCollectionsRoute
  '/backend/commerce': typeof BackendCommerceRoute
  '/backend/communications': typeof BackendCommunicationsRoute
  '/backend/content': typeof BackendContentRoute
  '/backend/data-transfer': typeof BackendDataTransferRoute
  '/backend/email-templates': typeof BackendEmailTemplatesRoute
  '/backend/feature-cards': typeof BackendFeatureCardsRoute
  '/backend/hero-slides': typeof BackendHeroSlidesRoute
  '/backend/homepage': typeof BackendHomepageRoute
  '/backend/homepage-sections': typeof BackendHomepageSectionsRoute
  '/backend/integrations': typeof BackendIntegrationsRoute
  '/backend/lifestyle-cards': typeof BackendLifestyleCardsRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/nav-links': typeof BackendNavLinksRoute
  '/backend/newsletter': typeof BackendNewsletterRoute
  '/backend/orders': typeof BackendOrdersRoute
  '/backend/pages': typeof BackendPagesRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/site-settings': typeof BackendSiteSettingsRoute
  '/backend/submissions': typeof BackendSubmissionsRoute
  '/backend/users': typeof BackendUsersRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/backend/': typeof BackendIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/backend'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/$'
    | '/backend/catalog'
    | '/backend/categories'
    | '/backend/checkout'
    | '/backend/collections'
    | '/backend/commerce'
    | '/backend/communications'
    | '/backend/content'
    | '/backend/data-transfer'
    | '/backend/email-templates'
    | '/backend/feature-cards'
    | '/backend/hero-slides'
    | '/backend/homepage'
    | '/backend/homepage-sections'
    | '/backend/integrations'
    | '/backend/lifestyle-cards'
    | '/backend/login'
    | '/backend/media'
    | '/backend/nav-links'
    | '/backend/newsletter'
    | '/backend/orders'
    | '/backend/pages'
    | '/backend/products'
    | '/backend/settings'
    | '/backend/site-settings'
    | '/backend/submissions'
    | '/backend/users'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/backend/'
    | '/bundles/'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/$'
    | '/backend/catalog'
    | '/backend/categories'
    | '/backend/checkout'
    | '/backend/collections'
    | '/backend/commerce'
    | '/backend/communications'
    | '/backend/content'
    | '/backend/data-transfer'
    | '/backend/email-templates'
    | '/backend/feature-cards'
    | '/backend/hero-slides'
    | '/backend/homepage'
    | '/backend/homepage-sections'
    | '/backend/integrations'
    | '/backend/lifestyle-cards'
    | '/backend/login'
    | '/backend/media'
    | '/backend/nav-links'
    | '/backend/newsletter'
    | '/backend/orders'
    | '/backend/pages'
    | '/backend/products'
    | '/backend/settings'
    | '/backend/site-settings'
    | '/backend/submissions'
    | '/backend/users'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin'
    | '/backend'
    | '/bundles'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/backend'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/$'
    | '/backend/catalog'
    | '/backend/categories'
    | '/backend/checkout'
    | '/backend/collections'
    | '/backend/commerce'
    | '/backend/communications'
    | '/backend/content'
    | '/backend/data-transfer'
    | '/backend/email-templates'
    | '/backend/feature-cards'
    | '/backend/hero-slides'
    | '/backend/homepage'
    | '/backend/homepage-sections'
    | '/backend/integrations'
    | '/backend/lifestyle-cards'
    | '/backend/login'
    | '/backend/media'
    | '/backend/nav-links'
    | '/backend/newsletter'
    | '/backend/orders'
    | '/backend/pages'
    | '/backend/products'
    | '/backend/settings'
    | '/backend/site-settings'
    | '/backend/submissions'
    | '/backend/users'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/backend/'
    | '/bundles/'
    | '/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BackendRouteRoute: typeof BackendRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  SearchRoute: typeof SearchRoute
  BundleSlugRoute: typeof BundleSlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/': {
      id: '/backend/'
      path: '/'
      fullPath: '/backend/'
      preLoaderRoute: typeof BackendIndexRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/users': {
      id: '/backend/users'
      path: '/users'
      fullPath: '/backend/users'
      preLoaderRoute: typeof BackendUsersRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/submissions': {
      id: '/backend/submissions'
      path: '/submissions'
      fullPath: '/backend/submissions'
      preLoaderRoute: typeof BackendSubmissionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/site-settings': {
      id: '/backend/site-settings'
      path: '/site-settings'
      fullPath: '/backend/site-settings'
      preLoaderRoute: typeof BackendSiteSettingsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/settings': {
      id: '/backend/settings'
      path: '/settings'
      fullPath: '/backend/settings'
      preLoaderRoute: typeof BackendSettingsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/products': {
      id: '/backend/products'
      path: '/products'
      fullPath: '/backend/products'
      preLoaderRoute: typeof BackendProductsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/pages': {
      id: '/backend/pages'
      path: '/pages'
      fullPath: '/backend/pages'
      preLoaderRoute: typeof BackendPagesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/orders': {
      id: '/backend/orders'
      path: '/orders'
      fullPath: '/backend/orders'
      preLoaderRoute: typeof BackendOrdersRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/newsletter': {
      id: '/backend/newsletter'
      path: '/newsletter'
      fullPath: '/backend/newsletter'
      preLoaderRoute: typeof BackendNewsletterRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/nav-links': {
      id: '/backend/nav-links'
      path: '/nav-links'
      fullPath: '/backend/nav-links'
      preLoaderRoute: typeof BackendNavLinksRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/media': {
      id: '/backend/media'
      path: '/media'
      fullPath: '/backend/media'
      preLoaderRoute: typeof BackendMediaRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/login': {
      id: '/backend/login'
      path: '/login'
      fullPath: '/backend/login'
      preLoaderRoute: typeof BackendLoginRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/lifestyle-cards': {
      id: '/backend/lifestyle-cards'
      path: '/lifestyle-cards'
      fullPath: '/backend/lifestyle-cards'
      preLoaderRoute: typeof BackendLifestyleCardsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/integrations': {
      id: '/backend/integrations'
      path: '/integrations'
      fullPath: '/backend/integrations'
      preLoaderRoute: typeof BackendIntegrationsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/homepage-sections': {
      id: '/backend/homepage-sections'
      path: '/homepage-sections'
      fullPath: '/backend/homepage-sections'
      preLoaderRoute: typeof BackendHomepageSectionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/homepage': {
      id: '/backend/homepage'
      path: '/homepage'
      fullPath: '/backend/homepage'
      preLoaderRoute: typeof BackendHomepageRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/hero-slides': {
      id: '/backend/hero-slides'
      path: '/hero-slides'
      fullPath: '/backend/hero-slides'
      preLoaderRoute: typeof BackendHeroSlidesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/feature-cards': {
      id: '/backend/feature-cards'
      path: '/feature-cards'
      fullPath: '/backend/feature-cards'
      preLoaderRoute: typeof BackendFeatureCardsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/email-templates': {
      id: '/backend/email-templates'
      path: '/email-templates'
      fullPath: '/backend/email-templates'
      preLoaderRoute: typeof BackendEmailTemplatesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/data-transfer': {
      id: '/backend/data-transfer'
      path: '/data-transfer'
      fullPath: '/backend/data-transfer'
      preLoaderRoute: typeof BackendDataTransferRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content': {
      id: '/backend/content'
      path: '/content'
      fullPath: '/backend/content'
      preLoaderRoute: typeof BackendContentRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/communications': {
      id: '/backend/communications'
      path: '/communications'
      fullPath: '/backend/communications'
      preLoaderRoute: typeof BackendCommunicationsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/commerce': {
      id: '/backend/commerce'
      path: '/commerce'
      fullPath: '/backend/commerce'
      preLoaderRoute: typeof BackendCommerceRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/collections': {
      id: '/backend/collections'
      path: '/collections'
      fullPath: '/backend/collections'
      preLoaderRoute: typeof BackendCollectionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/checkout': {
      id: '/backend/checkout'
      path: '/checkout'
      fullPath: '/backend/checkout'
      preLoaderRoute: typeof BackendCheckoutRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/categories': {
      id: '/backend/categories'
      path: '/categories'
      fullPath: '/backend/categories'
      preLoaderRoute: typeof BackendCategoriesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/catalog': {
      id: '/backend/catalog'
      path: '/catalog'
      fullPath: '/backend/catalog'
      preLoaderRoute: typeof BackendCatalogRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BackendRouteRouteChildren {
  BackendCatalogRoute: typeof BackendCatalogRoute
  BackendCategoriesRoute: typeof BackendCategoriesRoute
  BackendCheckoutRoute: typeof BackendCheckoutRoute
  BackendCollectionsRoute: typeof BackendCollectionsRoute
  BackendCommerceRoute: typeof BackendCommerceRoute
  BackendCommunicationsRoute: typeof BackendCommunicationsRoute
  BackendContentRoute: typeof BackendContentRoute
  BackendDataTransferRoute: typeof BackendDataTransferRoute
  BackendEmailTemplatesRoute: typeof BackendEmailTemplatesRoute
  BackendFeatureCardsRoute: typeof BackendFeatureCardsRoute
  BackendHeroSlidesRoute: typeof BackendHeroSlidesRoute
  BackendHomepageRoute: typeof BackendHomepageRoute
  BackendHomepageSectionsRoute: typeof BackendHomepageSectionsRoute
  BackendIntegrationsRoute: typeof BackendIntegrationsRoute
  BackendLifestyleCardsRoute: typeof BackendLifestyleCardsRoute
  BackendLoginRoute: typeof BackendLoginRoute
  BackendMediaRoute: typeof BackendMediaRoute
  BackendNavLinksRoute: typeof BackendNavLinksRoute
  BackendNewsletterRoute: typeof BackendNewsletterRoute
  BackendOrdersRoute: typeof BackendOrdersRoute
  BackendPagesRoute: typeof BackendPagesRoute
  BackendProductsRoute: typeof BackendProductsRoute
  BackendSettingsRoute: typeof BackendSettingsRoute
  BackendSiteSettingsRoute: typeof BackendSiteSettingsRoute
  BackendSubmissionsRoute: typeof BackendSubmissionsRoute
  BackendUsersRoute: typeof BackendUsersRoute
  BackendIndexRoute: typeof BackendIndexRoute
}

const BackendRouteRouteChildren: BackendRouteRouteChildren = {
  BackendCatalogRoute: BackendCatalogRoute,
  BackendCategoriesRoute: BackendCategoriesRoute,
  BackendCheckoutRoute: BackendCheckoutRoute,
  BackendCollectionsRoute: BackendCollectionsRoute,
  BackendCommerceRoute: BackendCommerceRoute,
  BackendCommunicationsRoute: BackendCommunicationsRoute,
  BackendContentRoute: BackendContentRoute,
  BackendDataTransferRoute: BackendDataTransferRoute,
  BackendEmailTemplatesRoute: BackendEmailTemplatesRoute,
  BackendFeatureCardsRoute: BackendFeatureCardsRoute,
  BackendHeroSlidesRoute: BackendHeroSlidesRoute,
  BackendHomepageRoute: BackendHomepageRoute,
  BackendHomepageSectionsRoute: BackendHomepageSectionsRoute,
  BackendIntegrationsRoute: BackendIntegrationsRoute,
  BackendLifestyleCardsRoute: BackendLifestyleCardsRoute,
  BackendLoginRoute: BackendLoginRoute,
  BackendMediaRoute: BackendMediaRoute,
  BackendNavLinksRoute: BackendNavLinksRoute,
  BackendNewsletterRoute: BackendNewsletterRoute,
  BackendOrdersRoute: BackendOrdersRoute,
  BackendPagesRoute: BackendPagesRoute,
  BackendProductsRoute: BackendProductsRoute,
  BackendSettingsRoute: BackendSettingsRoute,
  BackendSiteSettingsRoute: BackendSiteSettingsRoute,
  BackendSubmissionsRoute: BackendSubmissionsRoute,
  BackendUsersRoute: BackendUsersRoute,
  BackendIndexRoute: BackendIndexRoute,
}

const BackendRouteRouteWithChildren = BackendRouteRoute._addFileChildren(
  BackendRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BackendRouteRoute: BackendRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  SearchRoute: SearchRoute,
  BundleSlugRoute: BundleSlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BundlesIndexRoute: BundlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
