/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BundlesIndexRouteImport } from './routes/bundles/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as BundleSlugRouteImport } from './routes/bundle/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin/site-settings'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminNavLinksRouteImport } from './routes/admin/nav-links'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLifestyleCardsRouteImport } from './routes/admin/lifestyle-cards'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminHomepageSectionsRouteImport } from './routes/admin/homepage-sections'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminHeroSlidesRouteImport } from './routes/admin/hero-slides'
import { Route as AdminFeatureCardsRouteImport } from './routes/admin/feature-cards'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin/email-templates'
import { Route as AdminDataTransferRouteImport } from './routes/admin/data-transfer'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCommunicationsRouteImport } from './routes/admin/communications'
import { Route as AdminCommerceRouteImport } from './routes/admin/commerce'
import { Route as AdminCollectionsRouteImport } from './routes/admin/collections'
import { Route as AdminCheckoutRouteImport } from './routes/admin/checkout'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavLinksRoute = AdminNavLinksRouteImport.update({
  id: '/nav-links',
  path: '/nav-links',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLifestyleCardsRoute = AdminLifestyleCardsRouteImport.update({
  id: '/lifestyle-cards',
  path: '/lifestyle-cards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageSectionsRoute = AdminHomepageSectionsRouteImport.update({
  id: '/homepage-sections',
  path: '/homepage-sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHeroSlidesRoute = AdminHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeatureCardsRoute = AdminFeatureCardsRouteImport.update({
  id: '/feature-cards',
  path: '/feature-cards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataTransferRoute = AdminDataTransferRouteImport.update({
  id: '/data-transfer',
  path: '/data-transfer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommerceRoute = AdminCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCheckoutRoute = AdminCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/data-transfer': typeof AdminDataTransferRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/feature-cards': typeof AdminFeatureCardsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-sections': typeof AdminHomepageSectionsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/lifestyle-cards': typeof AdminLifestyleCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav-links': typeof AdminNavLinksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/data-transfer': typeof AdminDataTransferRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/feature-cards': typeof AdminFeatureCardsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-sections': typeof AdminHomepageSectionsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/lifestyle-cards': typeof AdminLifestyleCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav-links': typeof AdminNavLinksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/bundles': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/data-transfer': typeof AdminDataTransferRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/feature-cards': typeof AdminFeatureCardsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-sections': typeof AdminHomepageSectionsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/lifestyle-cards': typeof AdminLifestyleCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav-links': typeof AdminNavLinksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/checkout'
    | '/admin/collections'
    | '/admin/commerce'
    | '/admin/communications'
    | '/admin/content'
    | '/admin/data-transfer'
    | '/admin/email-templates'
    | '/admin/feature-cards'
    | '/admin/hero-slides'
    | '/admin/homepage'
    | '/admin/homepage-sections'
    | '/admin/integrations'
    | '/admin/lifestyle-cards'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav-links'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/submissions'
    | '/admin/users'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/bundles/'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/checkout'
    | '/admin/collections'
    | '/admin/commerce'
    | '/admin/communications'
    | '/admin/content'
    | '/admin/data-transfer'
    | '/admin/email-templates'
    | '/admin/feature-cards'
    | '/admin/hero-slides'
    | '/admin/homepage'
    | '/admin/homepage-sections'
    | '/admin/integrations'
    | '/admin/lifestyle-cards'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav-links'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/submissions'
    | '/admin/users'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin'
    | '/bundles'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/checkout'
    | '/admin/collections'
    | '/admin/commerce'
    | '/admin/communications'
    | '/admin/content'
    | '/admin/data-transfer'
    | '/admin/email-templates'
    | '/admin/feature-cards'
    | '/admin/hero-slides'
    | '/admin/homepage'
    | '/admin/homepage-sections'
    | '/admin/integrations'
    | '/admin/lifestyle-cards'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav-links'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/submissions'
    | '/admin/users'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/bundles/'
    | '/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  SearchRoute: typeof SearchRoute
  BundleSlugRoute: typeof BundleSlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nav-links': {
      id: '/admin/nav-links'
      path: '/nav-links'
      fullPath: '/admin/nav-links'
      preLoaderRoute: typeof AdminNavLinksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lifestyle-cards': {
      id: '/admin/lifestyle-cards'
      path: '/lifestyle-cards'
      fullPath: '/admin/lifestyle-cards'
      preLoaderRoute: typeof AdminLifestyleCardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage-sections': {
      id: '/admin/homepage-sections'
      path: '/homepage-sections'
      fullPath: '/admin/homepage-sections'
      preLoaderRoute: typeof AdminHomepageSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hero-slides': {
      id: '/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AdminHeroSlidesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feature-cards': {
      id: '/admin/feature-cards'
      path: '/feature-cards'
      fullPath: '/admin/feature-cards'
      preLoaderRoute: typeof AdminFeatureCardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-transfer': {
      id: '/admin/data-transfer'
      path: '/data-transfer'
      fullPath: '/admin/data-transfer'
      preLoaderRoute: typeof AdminDataTransferRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commerce': {
      id: '/admin/commerce'
      path: '/commerce'
      fullPath: '/admin/commerce'
      preLoaderRoute: typeof AdminCommerceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checkout': {
      id: '/admin/checkout'
      path: '/checkout'
      fullPath: '/admin/checkout'
      preLoaderRoute: typeof AdminCheckoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCheckoutRoute: typeof AdminCheckoutRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCommerceRoute: typeof AdminCommerceRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDataTransferRoute: typeof AdminDataTransferRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFeatureCardsRoute: typeof AdminFeatureCardsRoute
  AdminHeroSlidesRoute: typeof AdminHeroSlidesRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminHomepageSectionsRoute: typeof AdminHomepageSectionsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLifestyleCardsRoute: typeof AdminLifestyleCardsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavLinksRoute: typeof AdminNavLinksRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCheckoutRoute: AdminCheckoutRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCommerceRoute: AdminCommerceRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDataTransferRoute: AdminDataTransferRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFeatureCardsRoute: AdminFeatureCardsRoute,
  AdminHeroSlidesRoute: AdminHeroSlidesRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminHomepageSectionsRoute: AdminHomepageSectionsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLifestyleCardsRoute: AdminLifestyleCardsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavLinksRoute: AdminNavLinksRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  SearchRoute: SearchRoute,
  BundleSlugRoute: BundleSlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BundlesIndexRoute: BundlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
